services:
    # image project
    app:
        container_name: simulotto-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - .:/var/www
        networks:
            - simulotto

    # nginx
    nginx:
        container_name: simulotto-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - simulotto

    # db mysql
    postgres_principal:
        container_name: simulotto-postgres-principal
        image: postgres:15
        restart: unless-stopped
        environment:
            POSTGRES_DB: simulotto
            POSTGRES_USER: simulotto
            POSTGRES_PASSWORD: simulotto
        volumes:
            - ./.docker/postgres/principal:/var/lib/postgresql/data
            - ./docker-compose/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
        ports:
            - "5432:5432"
        networks:
            - simulotto

    postgres_auditoria:
        container_name: simulotto-postgres-auditoria
        image: postgres:15
        restart: unless-stopped
        environment:
            POSTGRES_DB: simulotto
            POSTGRES_USER: simulotto
            POSTGRES_PASSWORD: simulotto
        volumes:
            - ./.docker/postgres/auditoria:/var/lib/postgresql/data
            - ./docker-compose/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
        ports:
            - "5433:5432"
        networks:
            - simulotto

networks:
    simulotto:
        driver: bridge
